### ISSUE TITLE
No example given for SDK: International Autocomplete

### ISSUE THREAD

**Issue by WellSky-MaryWelch** [smartystreets/smartystreets-javascript-sdk#42]
There doesn't seem to be an example listed for how to use/access the International Address Autocomplete using the SDK.  https://github.com/smartystreets/smartystreets-javascript-sdk/tree/master/examples

**Comment by mattsafish** [comment]
https://github.com/smartystreets/smartystreets-javascript-sdk/blob/master/examples/international_address_autocomplete.js

Shoutout @alexkess101 for the example.

However, the types have not been updated for the javascript-sdk and don't include internationalAddressAutocomplete.

**Comment by alexkess101** [comment]
@mattsafish could you clarify what you mean when you say the types have not been updated? Are you asking for typescript examples as well?

**Comment by mattsafish** [comment]
@alexkess101 the type definitions for international address autocomplete are not in the most recently available @types/smartystreets-javascript-sdk. I commented on this issue since I believe it pertained to the nature of international address autocomplete being a recent addition, that in addition to the example only recently being added @types has not been accordingly updated. Your JavaScript example worked just fine for me using import syntax after I declared the types manually with help from your example and the source code. Sorry for not being clear.

**Comment by camiblanch** [comment]
@mattsafish Are you referring to the definitions seen [here?](https://www.npmjs.com/package/@types/smartystreets-javascript-sdk)

**Comment by mattsafish** [comment]
@camiblanch Yes those

**Comment by camiblanch** [comment]
@mattsafish SmartyStreets didn't create the those typescript definitions that you see and we don't currently have plans to maintain them. I recommend creating a pull request to the typescript definitions repository [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/smartystreets-javascript-sdk) or contacting [@newbish](https://github.com/newbish) who created the original typescript definitions for smartystreets-javascript-sdk.
